---
settings:
  name: NetApp data services
  platform: cloud
  search: console-relnotes,console-setup-admin,storage-management-cloud-volumes-ontap,storage-management-ontap-onprem,storage-management-azure-netapp-files,storage-management-fsx-ontap,storage-management-cloud-volumes-service-gcp,data-services-backup-recovery,data-services-copy-sync,data-services-data-classification,data-services-cloud-tiering,data-services-replication,console-automation,cloud-volumes-ontap-relnotes,storage-management-storagegrid,storage-management-e-series,storage-management-s3-storage,console-lifecycle-planning,console-license-subscriptions,storage-management-blob-storage,console-volume-caching,data-services-disaster-recovery,storage-management-blob-storage,storage-management-google-cloud-storage,netapp-automation,data-services-ransomware-resilience,console-software-updates,console-alerts,workload-setup-admin,workload-fsx-ontap,workload-databases,workload-genai,workload-vmware
  internal:
    pdf_enabled: false
    lipi_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: false
    lipi_enabled: false
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: NetAppコンソール
    url: "../console-setup-admin/index.html"
  - title: ストレージ管理
    url: "../storage-management-family/index.html"
  - title: リリース ノート
    url: "../console-relnotes/index.html"
  - title: バックアップとリカバリ
    url: "../data-services-backup-recovery/index.html"
  - title: クラウド階層化
    url: "../data-services-cloud-tiering/index.html"
  - title: コピーと同期
    url: "../data-services-copy-sync/index.html"
  - title: データ分類
    url: "../data-services-data-classification/index.html"
  - title: ディザスタ リカバリ
    url: "../data-services-disaster-recovery/index.html"
  - title: ランサムウェア耐性
    url: "../data-services-ransomware-resilience/index.html"
  - title: レプリケーション
    url: "../data-services-replication/index.html"
  - title: ボリュームキャッシュ
    url: "../data-services-volume-caching/index.html"
  - title: ワークロード
    url: "../workload-family"
